# Generated by Django 4.2.13 on 2024-06-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='actual_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
