# Generated by Django 4.2.13 on 2024-06-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_alter_income_actual_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cashamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cardamount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
