# Generated by Django 4.2.13 on 2024-06-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_savings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Savings',
            new_name='Saving',
        ),
    ]
